/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTransacoesRouteImport } from './routes/_layout/transacoes'
import { Route as LayoutSimulacoesRouteImport } from './routes/_layout/simulacoes'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPortfolioRouteImport } from './routes/_layout/portfolio'
import { Route as LayoutOrcamentoRouteImport } from './routes/_layout/orcamento'
import { Route as LayoutMetasRouteImport } from './routes/_layout/metas'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutInvestimentosRouteImport } from './routes/_layout/investimentos'
import { Route as LayoutConquistasRouteImport } from './routes/_layout/conquistas'
import { Route as LayoutConfiguracoesRouteImport } from './routes/_layout/configuracoes'
import { Route as LayoutCaixinhasRouteImport } from './routes/_layout/caixinhas'
import { Route as LayoutAnaliseRouteImport } from './routes/_layout/analise'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransacoesRoute = LayoutTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSimulacoesRoute = LayoutSimulacoesRouteImport.update({
  id: '/simulacoes',
  path: '/simulacoes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioRoute = LayoutPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrcamentoRoute = LayoutOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMetasRoute = LayoutMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInvestimentosRoute = LayoutInvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConquistasRoute = LayoutConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfiguracoesRoute = LayoutConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCaixinhasRoute = LayoutCaixinhasRouteImport.update({
  id: '/caixinhas',
  path: '/caixinhas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnaliseRoute = LayoutAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analise': typeof LayoutAnaliseRoute
  '/caixinhas': typeof LayoutCaixinhasRoute
  '/configuracoes': typeof LayoutConfiguracoesRoute
  '/conquistas': typeof LayoutConquistasRoute
  '/investimentos': typeof LayoutInvestimentosRoute
  '/items': typeof LayoutItemsRoute
  '/metas': typeof LayoutMetasRoute
  '/orcamento': typeof LayoutOrcamentoRoute
  '/portfolio': typeof LayoutPortfolioRoute
  '/settings': typeof LayoutSettingsRoute
  '/simulacoes': typeof LayoutSimulacoesRoute
  '/transacoes': typeof LayoutTransacoesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/analise': typeof LayoutAnaliseRoute
  '/caixinhas': typeof LayoutCaixinhasRoute
  '/configuracoes': typeof LayoutConfiguracoesRoute
  '/conquistas': typeof LayoutConquistasRoute
  '/investimentos': typeof LayoutInvestimentosRoute
  '/items': typeof LayoutItemsRoute
  '/metas': typeof LayoutMetasRoute
  '/orcamento': typeof LayoutOrcamentoRoute
  '/portfolio': typeof LayoutPortfolioRoute
  '/settings': typeof LayoutSettingsRoute
  '/simulacoes': typeof LayoutSimulacoesRoute
  '/transacoes': typeof LayoutTransacoesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/analise': typeof LayoutAnaliseRoute
  '/_layout/caixinhas': typeof LayoutCaixinhasRoute
  '/_layout/configuracoes': typeof LayoutConfiguracoesRoute
  '/_layout/conquistas': typeof LayoutConquistasRoute
  '/_layout/investimentos': typeof LayoutInvestimentosRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/metas': typeof LayoutMetasRoute
  '/_layout/orcamento': typeof LayoutOrcamentoRoute
  '/_layout/portfolio': typeof LayoutPortfolioRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/simulacoes': typeof LayoutSimulacoesRoute
  '/_layout/transacoes': typeof LayoutTransacoesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analise'
    | '/caixinhas'
    | '/configuracoes'
    | '/conquistas'
    | '/investimentos'
    | '/items'
    | '/metas'
    | '/orcamento'
    | '/portfolio'
    | '/settings'
    | '/simulacoes'
    | '/transacoes'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/analise'
    | '/caixinhas'
    | '/configuracoes'
    | '/conquistas'
    | '/investimentos'
    | '/items'
    | '/metas'
    | '/orcamento'
    | '/portfolio'
    | '/settings'
    | '/simulacoes'
    | '/transacoes'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/analise'
    | '/_layout/caixinhas'
    | '/_layout/configuracoes'
    | '/_layout/conquistas'
    | '/_layout/investimentos'
    | '/_layout/items'
    | '/_layout/metas'
    | '/_layout/orcamento'
    | '/_layout/portfolio'
    | '/_layout/settings'
    | '/_layout/simulacoes'
    | '/_layout/transacoes'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transacoes': {
      id: '/_layout/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof LayoutTransacoesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/simulacoes': {
      id: '/_layout/simulacoes'
      path: '/simulacoes'
      fullPath: '/simulacoes'
      preLoaderRoute: typeof LayoutSimulacoesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio': {
      id: '/_layout/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof LayoutPortfolioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orcamento': {
      id: '/_layout/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof LayoutOrcamentoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/metas': {
      id: '/_layout/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof LayoutMetasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/investimentos': {
      id: '/_layout/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof LayoutInvestimentosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/conquistas': {
      id: '/_layout/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof LayoutConquistasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configuracoes': {
      id: '/_layout/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof LayoutConfiguracoesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/caixinhas': {
      id: '/_layout/caixinhas'
      path: '/caixinhas'
      fullPath: '/caixinhas'
      preLoaderRoute: typeof LayoutCaixinhasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analise': {
      id: '/_layout/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof LayoutAnaliseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAnaliseRoute: typeof LayoutAnaliseRoute
  LayoutCaixinhasRoute: typeof LayoutCaixinhasRoute
  LayoutConfiguracoesRoute: typeof LayoutConfiguracoesRoute
  LayoutConquistasRoute: typeof LayoutConquistasRoute
  LayoutInvestimentosRoute: typeof LayoutInvestimentosRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMetasRoute: typeof LayoutMetasRoute
  LayoutOrcamentoRoute: typeof LayoutOrcamentoRoute
  LayoutPortfolioRoute: typeof LayoutPortfolioRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSimulacoesRoute: typeof LayoutSimulacoesRoute
  LayoutTransacoesRoute: typeof LayoutTransacoesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAnaliseRoute: LayoutAnaliseRoute,
  LayoutCaixinhasRoute: LayoutCaixinhasRoute,
  LayoutConfiguracoesRoute: LayoutConfiguracoesRoute,
  LayoutConquistasRoute: LayoutConquistasRoute,
  LayoutInvestimentosRoute: LayoutInvestimentosRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMetasRoute: LayoutMetasRoute,
  LayoutOrcamentoRoute: LayoutOrcamentoRoute,
  LayoutPortfolioRoute: LayoutPortfolioRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSimulacoesRoute: LayoutSimulacoesRoute,
  LayoutTransacoesRoute: LayoutTransacoesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
